import random
def statefunc(statenum):
    print(" ")
    statenum = random.choice(list)
    print(statenum)
    list.remove(statenum)
    input()
list = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]
print("50 State List Game, Press enter for next state.")
print(" ")
input("Press eneter to begin")
statefunc(1)
statefunc(2)
statefunc(3)
statefunc(4)
statefunc(5)
statefunc(6)
statefunc(7)
statefunc(8)
statefunc(9)
statefunc(10)
statefunc(11)
statefunc(12)
statefunc(13)
statefunc(14)
statefunc(15)
statefunc(16)
statefunc(17)
statefunc(18)
statefunc(19)
statefunc(20)
statefunc(21)
statefunc(22)
statefunc(23)
statefunc(24)
statefunc(25)
statefunc(26)
statefunc(27)
statefunc(28)
statefunc(29)
statefunc(30)
statefunc(31)
statefunc(32)
statefunc(33)
statefunc(34)
statefunc(35)
statefunc(36)
statefunc(37)
statefunc(38)
statefunc(39)
statefunc(40)
statefunc(41)
statefunc(42)
statefunc(43)
statefunc(44)
statefunc(45)
statefunc(46)
statefunc(47)
statefunc(48)
statefunc(49)
statefunc(50)
statefunc(51)
print("All States Complete")